# .travis.yml for cartogram.
#
# https://github.com/craigcitro/r-travis/wiki/Porting-to-native-R-support-in-Travis
before_install:
  - pwd
  - export CURWD=`pwd`
  - cd
  - sudo apt-get install libproj-dev
  - wget http://download.osgeo.org/gdal/2.0.1/gdal-2.0.1.tar.gz
  - tar zxf gdal-2.0.1.tar.gz
  - cd gdal-2.0.1
  - ./configure
  - make
  - sudo make install
  - sudo ldconfig
  - cd $CURWD

language: r

r:
  - oldrel
  - release
  - devel

sudo: required

cache: packages

notifications:
email:
on_success: change
on_failure: change
