# .travis.yml for cartogram.
#
# https://github.com/craigcitro/r-travis/wiki/Porting-to-native-R-support-in-Travis
language: r
r:
  - oldrel
  - release
  - devel
sudo: false
cache: packages
addons:
  apt:
    packages:
      - libgdal-dev
      - libgdal1-dev 
      - libgeos-dev 
      - libgeos++-dev 
      - libgsl0-dev 
      - libproj-dev 
      - libspatialite-dev 
      - netcdf-bin
notifications:
email:
on_success: change
on_failure: change
